@TemportalTables_Api_HostAddress = http://localhost:5045

POST {{TemportalTables_Api_HostAddress}}/orders
Content-Type: application/json
Current-User: "Leonardo Almeida"
{
    "Product": "TV SAMSUNG",
    "description": "TV SAMSUNG 85' QLED ULTRA HD",
    "unitPrice": 90010.00,
    "quantity": 1
}
###

PATCH {{TemportalTables_Api_HostAddress}}/orders/1
Content-Type: application/json
Current-User: "Eduardo Almeida"
{
    "Product": "TV SAMSUNG",
    "description": "TV SAMSUNG 98' QLED",
    "unitPrice": 200000.00,
    "quantity": 1
}
###

GET {{TemportalTables_Api_HostAddress}}/orders/1
###